language: node_js

node_js:
  - lts/*

env:
  global:
    - CC_TEST_REPORTER_ID=119c8d1e149551da825a26134c674e194f8ac311664e4af23eda97d12663cb4e

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT